### ISSUE TITLE
Pipeline de deploy

### ISSUE THREAD

**Issue by gomex** [descomplicando-terraform/jhtoigo-repo-produto#10]
- A criação do ECR deve acontecer antes do build
  - Ela pode ser movida pro groundwork
  - Ela pode ser movida para algum modulo a parte e rodar antes do build dentro desse pipeline mesmo
- Executar o terraform apply

**Comment by jhtoigo** [comment]
- [ ] Movido a criação do ECR para o groundwork\
 - [ ] Executado o terraform apply
